vim.g.mapleader = " "
vim.keymap.set("n", "<leader>cd", vim.cmd.Ex)
vim.keymap.set('n', '<leader>o', ':update<CR> :source<CR>')
vim.keymap.set('n', '<leader>w', ':write<CR>')
vim.keymap.set('n', '<leader>qq', ':quit<CR>')
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("n", "<C-k>", "<cmd>cnext<CR>zz")
vim.keymap.set("n", "<C-j>", "<cmd>cprev<CR>zz")
vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("v", "<leader>y", '"+y')
vim.keymap.set("n", "<leader>Y", '"+Y')
vim.keymap.set("n", "<leader>y", '"+y')
vim.keymap.set("n", "<leader>d", '"_d')
vim.keymap.set("v", "<leader>d", '"_d')
vim.keymap.set("x", "<leader>p", [["_dP]])
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>k", "<cmd>lnext<CR>zz")
vim.keymap.set("n", "<leader>j", "<cmd>lprev<CR>zz")
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
vim.keymap.set("n", "<C-j>", "<C-w>j", { desc = "Go to down split" })
vim.keymap.set("n", "<C-k>", "<C-w>k", { desc = "Go to up split" })
vim.keymap.set("n", "<C-h>", "<C-w>h", { desc = "Go to left split" })
vim.keymap.set("n", "<C-l>", "<C-w>l", { desc = "Go to right split" })
vim.keymap.set("n", "<leader>=", "<C-w>=", { desc = "Make splits equal size" })
vim.keymap.set("n", "<leader>gs", vim.cmd.Git, { desc = "vim fugitive git signs" })

-- Test runner keybinds (for Go)
vim.keymap.set("n", "<leader>tt", ":!go test ./...<CR>", { desc = "Run all tests" })
vim.keymap.set("n", "<leader>tf", ":!go test .<CR>", { desc = "Run tests in current package" })
vim.keymap.set("n", "<leader>tn", function()
  -- Get test name under cursor
  local line = vim.api.nvim_get_current_line()
  local test_name = line:match("func%s+(Test%w+)")
  if test_name then
    vim.cmd("!go test -run " .. test_name)
  else
    print("No test function found under cursor")
  end
end, { desc = "Run test under cursor" })
vim.keymap.set("n", "<leader>tc", ":!go test -cover ./...<CR>", { desc = "Run tests with coverage" })
vim.keymap.set("n", "<leader>tv", ":!go test -v ./...<CR>", { desc = "Run tests (verbose)" })
